const kanji = [
    {"key": "日本", "values": ["nihon", "nippon"]},
    {"key": "人", "values": ["hito"]},
    {"key": "火山", "values": ["kazan"]},
    {"key": "秋", "values": ["aki"]},
    {"key": "男", "values": ["otoko"]},
    {"key": "雨", "values": ["ame"]},
    {"key": "私", "values": ["watashi", "watakushi"]},
    {"key": "人口", "values": ["jinkou"]},
    {"key": "何", "values": ["nani"]},
    {"key": "気分", "values": ["kibun"]},
    {"key": "肉", "values": ["niku"]},
    {"key": "島", "values": ["shima"]},
    {"key": "一日", "values": ["ichinichi", "tsuitachi"]},
    {"key": "困惑", "values": ["konwaku"]},
    {"key": "本当", "values": ["hontou"]},
    {"key": "天ぷら", "values": ["tenpura"]},
    {"key": "危ない", "values": ["abunai"]},
    {"key": "朝", "values": ["asa"]},
    {"key": "島", "values": ["shima"]},
    {"key": "大変", "values": ["taihen"]},
    {"key": "時間", "values": ["jikan"]},
    {"key": "東京", "values": ["tokyo", "toukyou", "toukyo"]},
    {"key": "今日", "values": ["kyou"]},
    {"key": "今", "values": ["ima"]},
    {"key": "昨日", "values": ["kinou"]},
    {"key": "明日", "values": ["ashita"]},
    {"key": "明後日", "values": ["asatte"]},
    {"key": "一昨日", "values": ["ototoi"]},
    {"key": "犯人", "values": ["hannin", "han'nin"]},
    {"key": "家", "values": ["ie"]}
  ];

export default kanji;
